[package]
name = "test_headers"
version = "0.1.0"
authors = ["Todd Mortimer <todd@opennet.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0"
